### PR TITLE
Add Sprig templating capability to transforms and CombineFromComposite

### PR DESCRIPTION
**Pull request by phclark**
This add the ability to use sprig templates as a transform, or with CombineFromComposite instead of simple fmt. The benefit of this is similar to function-go-template, except that we can benefit from the power of templates within the patch-and-transform context.

### CODE REVIEW

**Comment by negz** [comment]
@phclark I'm a little wary of mixing Go templating into the P&T function. Would it not be reasonable to expect folks to use https://github.com/crossplane-contrib/function-go-templating if they wanted this kind of expressiveness?

**Comment by withnale** [comment]
Coming back around... I regard the below as a "simple use case" that is simple using this PR.

```yaml
        - type: CombineFromComposite
          toFieldPath: "spec.forProvider.projectId"
          combine:
            strategy: template
            variables:
              - fromFieldPath: metadata.name
                variableName: name
              - fromFieldPath: metadata.uid
                variableName: uid
            template:
              template: '{{ .name }}-{{ .uid | sha1sum | trunc 8 }}'
```

How would I approach this using the main branch version of `function-patch-and-transform`?

This "need" is in a composition file that is 1200 lines long already, so just moving it into `function-go-templating` isn't a quick option and having everything being a multiline yaml block removes the structure from the file potentially opening us up for a lot more uncaught errors.

**Comment by phisco** [comment]
@phclark, I think the point is that with this many other features would become redundant, e.g. most other string transforms could be replaced with just a string transform of type `Template`, and the rest could probably be replaced with the same + some `ToType` transform. I can see the value of a function that combines `function-patch-and-transform` and `function-go-templating`. The latter is better suited for creating new resources from scratch, with support for loops, ifs and other more powerful constructs, while the former is more effective at patching between resources and handling existing resources. But I think it would be better to think it from scratch rather than trying to fit it into this function.

**Comment by negz** [comment]
> How would I approach this using the main branch version of function-patch-and-transform?

You wouldn't. The goal of this function is not full expressiveness.

The intent behind P&T is to cover the simple "I need to copy data X from resource Y to resource Z" case. It was forced to grow more expressive (and thus hard to reason about) than that because there was no alternative. There are now alternatives in the form of other functions, including one specifically dedicated to Go templating. 

We need to cap the complexity of this function somewhere. Introducing a nested templating language with its own set of functions (in addition to the "first-class" transforms we already support) seems like a reasonable place to draw the line.

**Comment by negz** [comment]
My position here hasn't changed. I appreciate the effort, but I'm going to close this PR.

I think https://github.com/crossplane-contrib/function-go-templating/ is a great alternative to explore if you need this level of expressiveness.

**Pull request closed without merging**
